### PR TITLE
Bring in code from allennlp-guide-examples

### PR DESCRIPTION
**Pull request by epwalsh**
Brings the code from https://github.com/allenai/allennlp-guide-examples into here as @matt-gardner and I discussed.

### CODE REVIEW

**Review by matt-gardner — APPROVED** [review]
LGTM.  You may also want to double check the last section of the README - I think there's a link there that'll be broken after this PR.  The rest is probably ok.

**Comment by matt-gardner** [comment]
Also FYI @pdasigi - the `nla_semparse` code is moving directly into this repo.

**Comment by epwalsh** [comment]
I don't know if this will work properly with Binder. When I tried this:

image

Binder tried to build from the `Dockerfile`, which it shouldn't because that `Dockerfile` is just for the web app.

**Comment by epwalsh** [comment]
So I guess the question is: how do I tell Binder ignore the Dockerfile and just build it as a Python project?

**Comment by epwalsh** [comment]
Alright I think I fixed it by just renaming the Dockerfile to something else.

**Pull request merged**
